export const navigationLinks = [
	{ href: "/", text: "Home" },
	{ href: "/portfolio", text: "Portfolio" },
	{ href: "/about", text: "About" },
	{ href: "/contact", text: "Contact" },
];

export const testimonials = [
	{
		quote: "Our living room is now the perfect blend of elegance and comfort. The team's expertise exceeded all our expectations!",
		name: "Ravi Patel",
		designation: "Homeowner, Bengaluru",
		src: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=3560&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
	},
	{
		quote: "Transforming our office space into a modern, productive environment was seamless with their guidance. Highly recommended!",
		name: "Ananya Sharma",
		designation: "Entrepreneur, Ahmedabad",
		src: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=3540&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
	},
	{
		quote: "The kitchen makeover was a dream come true! Every corner reflects both beauty and functionality.",
		name: "Priya Iyer",
		designation: "Chef, Chennai",
		src: "https://images.unsplash.com/photo-1623582854588-d60de57fa33f?q=80&w=3540&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
	},
	{
		quote: "Thanks to their brilliant designs, our home now feels like a luxury retreat. Exceptional work!",
		name: "Arjun Mehta",
		designation: "Architect, Mumbai",
		src: "https://images.unsplash.com/photo-1636041293178-808a6762ab39?q=80&w=3464&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
	},
	{
		quote: "The attention to detail and thoughtful layout of our new home interior has left us speechless. Absolutely delighted!",
		name: "Neha Gupta",
		designation: "IT Professional, Delhi",
		src: "https://images.unsplash.com/photo-1624561172888-ac93c696e10c?q=80&w=2592&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
	},
];

export const portfolioData = {
	"Advantech Office": {
		title: "Advantech Office",
		src: "/Commercial/Advantech Office/1.webp",
		type: "Commercial",
		description:
			"A modern workspace designed to inspire creativity and collaboration, balancing functionality with cutting-edge design.",
		images: [
			"/Commercial/Advantech Office/1.webp",
			"/Commercial/Advantech Office/2.webp",
			"/Commercial/Advantech Office/3.webp",
			"/Commercial/Advantech Office/4.webp",
			"/Commercial/Advantech Office/5.webp",
			"/Commercial/Advantech Office/6.webp",
			"/Commercial/Advantech Office/7.webp",
			"/Commercial/Advantech Office/8.webp",
			"/Commercial/Advantech Office/9.webp",
			"/Commercial/Advantech Office/10.webp",
		],
	},
	"Fizz Club House": {
		title: "Fizz Club House",
		src: "/Commercial/Fizz Club House/1.webp",
		type: "Commercial",
		description:
			"A vibrant social hub combining contemporary aesthetics with a welcoming atmosphere for leisure and gatherings.",
		images: [
			"/Commercial/Fizz Club House/1.webp",
			"/Commercial/Fizz Club House/2.webp",
			"/Commercial/Fizz Club House/3.webp",
			"/Commercial/Fizz Club House/4.webp",
			"/Commercial/Fizz Club House/5.webp",
			"/Commercial/Fizz Club House/6.webp",
			"/Commercial/Fizz Club House/7.webp",
			"/Commercial/Fizz Club House/8.webp",
			"/Commercial/Fizz Club House/9.webp",
			"/Commercial/Fizz Club House/10.webp",
			"/Commercial/Fizz Club House/11.webp",
			"/Commercial/Fizz Club House/12.webp",
			"/Commercial/Fizz Club House/13.webp",
		],
	},
	Manjhu: {
		title: "Manjhu",
		src: "/Commercial/Manjhu/1.webp",
		type: "Commercial",
		description:
			"A dynamic commercial space that redefines professional environments with sleek finishes and innovative layouts.",
		images: [
			"/Commercial/Manjhu/1.webp",
			"/Commercial/Manjhu/2.webp",
			"/Commercial/Manjhu/3.webp",
			"/Commercial/Manjhu/4.webp",
			"/Commercial/Manjhu/5.webp",
			"/Commercial/Manjhu/6.webp",
			"/Commercial/Manjhu/7.webp",
			"/Commercial/Manjhu/8.webp",
		],
	},
	Realstate: {
		title: "Realstate",
		src: "/Commercial/Realstate/1.webp",
		type: "Commercial",
		description:
			"A sophisticated and versatile design tailored to meet the diverse needs of the real estate industry.",
		images: [
			"/Commercial/Realstate/1.webp",
			"/Commercial/Realstate/2.webp",
			"/Commercial/Realstate/3.webp",
			"/Commercial/Realstate/4.webp",
			"/Commercial/Realstate/5.webp",
			"/Commercial/Realstate/6.webp",
			"/Commercial/Realstate/7.webp",
			"/Commercial/Realstate/8.webp",
			"/Commercial/Realstate/9.webp",
			"/Commercial/Realstate/10.webp",
			"/Commercial/Realstate/11.webp",
			"/Commercial/Realstate/12.webp",
		],
	},
	"Fire Office": {
		title: "Fire Office",
		src: "/Commercial/Fire Office/1.webp",
		type: "Commercial",
		description:
			"A bold and contemporary office space featuring striking design elements and a focus on productivity.",
		images: [
			"/Commercial/Fire Office/1.webp",
			"/Commercial/Fire Office/2.webp",
			"/Commercial/Fire Office/3.webp",
			"/Commercial/Fire Office/4.webp",
			"/Commercial/Fire Office/5.webp",
			"/Commercial/Fire Office/6.webp",
			"/Commercial/Fire Office/7.webp",
			"/Commercial/Fire Office/8.webp",
			"/Commercial/Fire Office/9.webp",
			"/Commercial/Fire Office/10.webp",
			"/Commercial/Fire Office/11.webp",
			"/Commercial/Fire Office/12.webp",
		],
	},
	"Neha Vikram": {
		title: "Neha Vikram",
		src: "/Commercial/Neha Vikram/1.webp",
		type: "Commercial",
		description:
			"A chic and modern commercial space where style meets practicality, offering an inspiring environment.",
		images: [
			"/Commercial/Neha Vikram/1.webp",
			"/Commercial/Neha Vikram/2.webp",
			"/Commercial/Neha Vikram/3.webp",
			"/Commercial/Neha Vikram/4.webp",
			"/Commercial/Neha Vikram/5.webp",
			"/Commercial/Neha Vikram/6.webp",
			"/Commercial/Neha Vikram/7.webp",
			"/Commercial/Neha Vikram/8.webp",
		],
	},
	"Priynka Kolkata": {
		title: "Priynka Kolkata",
		src: "/Commercial/Priynka Kolkata/1.webp",
		type: "Commercial",
		description:
			"A thoughtfully designed commercial venue blending cultural charm with modern architectural trends.",
		images: [
			"/Commercial/Priynka Kolkata/1.webp",
			"/Commercial/Priynka Kolkata/2.webp",
			"/Commercial/Priynka Kolkata/3.webp",
			"/Commercial/Priynka Kolkata/4.webp",
			"/Commercial/Priynka Kolkata/5.webp",
			"/Commercial/Priynka Kolkata/6.webp",
			"/Commercial/Priynka Kolkata/7.webp",
			"/Commercial/Priynka Kolkata/8.webp",
			"/Commercial/Priynka Kolkata/9.webp",
		],
	},
	"Punjabi Dhaba": {
		title: "Punjabi Dhaba",
		src: "/Commercial/Punjabi Dhaba/1.webp",
		type: "Commercial",
		description:
			"A vibrant and authentic dining experience brought to life with rustic yet modern interiors.",
		images: [
			"/Commercial/Punjabi Dhaba/1.webp",
			"/Commercial/Punjabi Dhaba/2.webp",
			"/Commercial/Punjabi Dhaba/3.webp",
			"/Commercial/Punjabi Dhaba/4.webp",
			"/Commercial/Punjabi Dhaba/5.webp",
			"/Commercial/Punjabi Dhaba/6.webp",
			"/Commercial/Punjabi Dhaba/7.webp",
			"/Commercial/Punjabi Dhaba/8.webp",
			"/Commercial/Punjabi Dhaba/9.webp",
			"/Commercial/Punjabi Dhaba/10.webp",
			"/Commercial/Punjabi Dhaba/11.webp",
			"/Commercial/Punjabi Dhaba/12.webp",
			"/Commercial/Punjabi Dhaba/13.webp",
			"/Commercial/Punjabi Dhaba/14.webp",
			"/Commercial/Punjabi Dhaba/15.webp",
		],
	},
	Winntus: {
		title: "Winntus",
		src: "/Commercial/Winntus/1.webp",
		type: "Commercial",
		description:
			"A cutting-edge commercial design, seamlessly integrating functionality and aesthetic appeal.",
		images: [
			"/Commercial/Winntus/1.webp",
			"/Commercial/Winntus/2.webp",
			"/Commercial/Winntus/3.webp",
			"/Commercial/Winntus/4.webp",
			"/Commercial/Winntus/5.webp",
			"/Commercial/Winntus/6.webp",
			"/Commercial/Winntus/7.webp",
			"/Commercial/Winntus/8.webp",
			"/Commercial/Winntus/9.webp",
			"/Commercial/Winntus/10.webp",
		],
	},
	"Lico Industrial": {
		title: "Lico Industrial",
		src: "/Commercial/Lico Industrial/1.webp",
		type: "Commercial",
		description:
			"A robust and efficient industrial space crafted with precision and attention to operational needs.",
		images: [
			"/Commercial/Lico Industrial/1.webp",
			"/Commercial/Lico Industrial/2.webp",
			"/Commercial/Lico Industrial/3.webp",
			"/Commercial/Lico Industrial/4.webp",
			"/Commercial/Lico Industrial/5.webp",
			"/Commercial/Lico Industrial/6.webp",
			"/Commercial/Lico Industrial/7.webp",
			"/Commercial/Lico Industrial/8.webp",
			"/Commercial/Lico Industrial/9.webp",
			"/Commercial/Lico Industrial/10.webp",
			"/Commercial/Lico Industrial/11.webp",
			"/Commercial/Lico Industrial/12.webp",
			"/Commercial/Lico Industrial/13.webp",
			"/Commercial/Lico Industrial/14.webp",
			"/Commercial/Lico Industrial/15.webp",
		],
	},
	"Cafe In Delhi": {
		title: "Cafe In Delhi",
		src: "/Commercial/Cafe In Delhi/1.webp",
		type: "Commercial",
		description:
			"A cozy and stylish cafe ambiance, combining urban design with inviting warmth for an unforgettable experience.",
		images: [
			"/Commercial/Cafe In Delhi/1.webp",
			"/Commercial/Cafe In Delhi/2.webp",
			"/Commercial/Cafe In Delhi/3.webp",
			"/Commercial/Cafe In Delhi/4.webp",
			"/Commercial/Cafe In Delhi/5.webp",
			"/Commercial/Cafe In Delhi/6.webp",
			"/Commercial/Cafe In Delhi/7.webp",
			"/Commercial/Cafe In Delhi/8.webp",
			"/Commercial/Cafe In Delhi/9.webp",
		],
	},
	Museum: {
		title: "Museum",
		src: "/Commercial/Museum/9.webp",
		type: "Commercial",
		description:
			"A cultural showcase of elegance and creativity, designed to captivate visitors and enhance storytelling.",
		images: [
			"/Commercial/Museum/1.webp",
			"/Commercial/Museum/2.webp",
			"/Commercial/Museum/3.webp",
			"/Commercial/Museum/4.webp",
			"/Commercial/Museum/5.webp",
			"/Commercial/Museum/6.webp",
			"/Commercial/Museum/7.webp",
			"/Commercial/Museum/8.webp",
			"/Commercial/Museum/9.webp",
			"/Commercial/Museum/10.webp",
			"/Commercial/Museum/11.webp",
		],
	},
	"Shyam Kunj": {
		title: "Shyam Kunj",
		src: "/Residential/Shyam Kunj/1.webp",
		type: "Residential",
		description:
			"A luxurious haven blending timeless elegance with modern functionality, designed for ultimate comfort and sophistication.",
		images: [
			"/Residential/Shyam Kunj/1.webp",
			"/Residential/Shyam Kunj/2.webp",
			"/Residential/Shyam Kunj/3.webp",
			"/Residential/Shyam Kunj/4.webp",
			"/Residential/Shyam Kunj/5.webp",
			"/Residential/Shyam Kunj/6.webp",
			"/Residential/Shyam Kunj/7.webp",
			"/Residential/Shyam Kunj/8.webp",
			"/Residential/Shyam Kunj/9.webp",
			"/Residential/Shyam Kunj/10.webp",
			"/Residential/Shyam Kunj/11.webp",
			"/Residential/Shyam Kunj/12.webp",
			"/Residential/Shyam Kunj/13.webp",
			"/Residential/Shyam Kunj/14.webp",
			"/Residential/Shyam Kunj/15.webp",
		],
	},
	"Vaisnavi 2": {
		title: "Vaisnavi 2",
		src: "/Residential/Vaisnavi 2/1.webp",
		type: "Residential",
		description:
			"A serene and stylish residence featuring contemporary interiors that embrace natural light and clean aesthetics.",
		images: [
			"/Residential/Vaisnavi 2/1.webp",
			"/Residential/Vaisnavi 2/2.webp",
			"/Residential/Vaisnavi 2/3.webp",
			"/Residential/Vaisnavi 2/4.webp",
			"/Residential/Vaisnavi 2/5.webp",
			"/Residential/Vaisnavi 2/6.webp",
			"/Residential/Vaisnavi 2/7.webp",
			"/Residential/Vaisnavi 2/8.webp",
			"/Residential/Vaisnavi 2/9.webp",
			"/Residential/Vaisnavi 2/10.webp",
			"/Residential/Vaisnavi 2/11.webp",
			"/Residential/Vaisnavi 2/12.webp",
			"/Residential/Vaisnavi 2/13.webp",
			"/Residential/Vaisnavi 2/14.webp",
			"/Residential/Vaisnavi 2/15.webp",
			"/Residential/Vaisnavi 2/16.webp",
			"/Residential/Vaisnavi 2/17.webp",
			"/Residential/Vaisnavi 2/18.webp",
			"/Residential/Vaisnavi 2/19.webp",
		],
	},
	Abhishek: {
		title: "Abhishek",
		src: "/Residential/Abhishek/2.webp",
		type: "Residential",
		description:
			"A thoughtfully curated home with a perfect mix of bold accents and minimalist design principles.",
		images: [
			"/Residential/Abhishek/1.webp",
			"/Residential/Abhishek/2.webp",
			"/Residential/Abhishek/3.webp",
			"/Residential/Abhishek/4.webp",
			"/Residential/Abhishek/5.webp",
			"/Residential/Abhishek/6.webp",
			"/Residential/Abhishek/7.webp",
			"/Residential/Abhishek/8.webp",
			"/Residential/Abhishek/9.webp",
			"/Residential/Abhishek/10.webp",
			"/Residential/Abhishek/11.webp",
			"/Residential/Abhishek/12.webp",
			"/Residential/Abhishek/13.webp",
			"/Residential/Abhishek/14.webp",
			"/Residential/Abhishek/15.webp",
			"/Residential/Abhishek/16.webp",
			"/Residential/Abhishek/17.webp",
			"/Residential/Abhishek/18.webp",
			"/Residential/Abhishek/19.webp",
			"/Residential/Abhishek/20.webp",
			"/Residential/Abhishek/21.webp",
			"/Residential/Abhishek/22.webp",
			"/Residential/Abhishek/23.webp",
			"/Residential/Abhishek/24.webp",
		],
	},
	Manjhunath: {
		title: "Manjhunath",
		src: "/Residential/Manjhunath/1.webp",
		type: "Residential",
		description:
			"A vibrant living space with creative layouts and a harmonious interplay of colors and textures.",
		images: [
			"/Residential/Manjhunath/1.webp",
			"/Residential/Manjhunath/2.webp",
			"/Residential/Manjhunath/3.webp",
			"/Residential/Manjhunath/4.webp",
			"/Residential/Manjhunath/5.webp",
			"/Residential/Manjhunath/6.webp",
			"/Residential/Manjhunath/7.webp",
			"/Residential/Manjhunath/8.webp",
			"/Residential/Manjhunath/9.webp",
		],
	},
	Meera: {
		title: "Meera",
		src: "/Residential/Meera/1.webp",
		type: "Residential",
		description:
			"A refined sanctuary with understated charm, designed to balance luxury with everyday practicality.",
		images: [
			"/Residential/Meera/1.webp",
			"/Residential/Meera/2.webp",
			"/Residential/Meera/3.webp",
			"/Residential/Meera/4.webp",
			"/Residential/Meera/5.webp",
			"/Residential/Meera/6.webp",
			"/Residential/Meera/7.webp",
			"/Residential/Meera/8.webp",
			"/Residential/Meera/9.webp",
			"/Residential/Meera/10.webp",
			"/Residential/Meera/11.webp",
			"/Residential/Meera/12.webp",
		],
	},
	Swetha: {
		title: "Swetha",
		src: "/Residential/Swetha/1.webp",
		type: "Residential",
		description:
			"A contemporary abode with meticulous attention to detail, offering a perfect blend of warmth and elegance.",
		images: [
			"/Residential/Swetha/1.webp",
			"/Residential/Swetha/2.webp",
			"/Residential/Swetha/3.webp",
			"/Residential/Swetha/4.webp",
			"/Residential/Swetha/5.webp",
			"/Residential/Swetha/6.webp",
			"/Residential/Swetha/7.webp",
			"/Residential/Swetha/8.webp",
			"/Residential/Swetha/9.webp",
			"/Residential/Swetha/10.webp",
			"/Residential/Swetha/11.webp",
			"/Residential/Swetha/12.webp",
			"/Residential/Swetha/13.webp",
		],
	},
	Nagarshini: {
		title: "Nagarshini",
		src: "/Residential/Nagarshini/1.webp",
		type: "Residential",
		description:
			"A modern retreat featuring innovative spatial design and an inviting atmosphere tailored for family living.",
		images: [
			"/Residential/Nagarshini/1.webp",
			"/Residential/Nagarshini/2.webp",
			"/Residential/Nagarshini/3.webp",
			"/Residential/Nagarshini/4.webp",
			"/Residential/Nagarshini/5.webp",
			"/Residential/Nagarshini/6.webp",
			"/Residential/Nagarshini/7.webp",
			"/Residential/Nagarshini/8.webp",
			"/Residential/Nagarshini/9.webp",
			"/Residential/Nagarshini/10.webp",
			"/Residential/Nagarshini/11.webp",
			"/Residential/Nagarshini/12.webp",
			"/Residential/Nagarshini/13.webp",
			"/Residential/Nagarshini/14.webp",
			"/Residential/Nagarshini/15.webp",
			"/Residential/Nagarshini/16.webp",
			"/Residential/Nagarshini/17.webp",
			"/Residential/Nagarshini/18.webp",
			"/Residential/Nagarshini/19.webp",
		],
	},
	"Bspoq Anser": {
		title: "Bspoq Anser",
		src: "/Residential/Bspoq Anser/1.webp",
		type: "Residential",
		description:
			"A bespoke residence showcasing custom designs and an artistic approach to modern living.",
		images: [
			"/Residential/Bspoq Anser/1.webp",
			"/Residential/Bspoq Anser/2.webp",
			"/Residential/Bspoq Anser/3.webp",
			"/Residential/Bspoq Anser/4.webp",
			"/Residential/Bspoq Anser/5.webp",
			"/Residential/Bspoq Anser/6.webp",
			"/Residential/Bspoq Anser/7.webp",
			"/Residential/Bspoq Anser/8.webp",
			"/Residential/Bspoq Anser/9.webp",
			"/Residential/Bspoq Anser/10.webp",
			"/Residential/Bspoq Anser/11.webp",
		],
	},
	Mushraf: {
		title: "Mushraf",
		src: "/Residential/Mushraf/1.webp",
		type: "Residential",
		description:
			"A striking home defined by bold contrasts and intricate detailing, creating a unique and inviting space.",
		images: [
			"/Residential/Mushraf/1.webp",
			"/Residential/Mushraf/2.webp",
			"/Residential/Mushraf/3.webp",
			"/Residential/Mushraf/4.webp",
			"/Residential/Mushraf/5.webp",
			"/Residential/Mushraf/6.webp",
			"/Residential/Mushraf/7.webp",
			"/Residential/Mushraf/8.webp",
			"/Residential/Mushraf/9.webp",
			"/Residential/Mushraf/10.webp",
			"/Residential/Mushraf/11.webp",
			"/Residential/Mushraf/12.webp",
			"/Residential/Mushraf/13.webp",
			"/Residential/Mushraf/14.webp",
			"/Residential/Mushraf/15.webp",
			"/Residential/Mushraf/16.webp",
			"/Residential/Mushraf/17.webp",
			"/Residential/Mushraf/18.webp",
			"/Residential/Mushraf/19.webp",
			"/Residential/Mushraf/20.webp",
		],
	},
	Praveen: {
		title: "Praveen",
		src: "/Residential/Praveen/1.webp",
		type: "Residential",
		description:
			"A cozy and elegant dwelling with thoughtful interiors designed to enhance everyday living experiences.",
		images: [
			"/Residential/Praveen/1.webp",
			"/Residential/Praveen/2.webp",
			"/Residential/Praveen/3.webp",
			"/Residential/Praveen/4.webp",
			"/Residential/Praveen/5.webp",
			"/Residential/Praveen/6.webp",
			"/Residential/Praveen/7.webp",
			"/Residential/Praveen/8.webp",
			"/Residential/Praveen/9.webp",
			"/Residential/Praveen/10.webp",
			"/Residential/Praveen/11.webp",
			"/Residential/Praveen/12.webp",
			"/Residential/Praveen/13.webp",
			"/Residential/Praveen/15.webp",
		],
	},
	Vaisnavi: {
		title: "Vaisnavi",
		src: "/Residential/Vaisnavi/1.webp",
		type: "Residential",
		description:
			"A stunning home crafted with clean lines, earthy tones, and a focus on functional luxury.",
		images: [
			"/Residential/Vaisnavi/1.webp",
			"/Residential/Vaisnavi/2.webp",
			"/Residential/Vaisnavi/3.webp",
			"/Residential/Vaisnavi/4.webp",
			"/Residential/Vaisnavi/5.webp",
			"/Residential/Vaisnavi/6.webp",
			"/Residential/Vaisnavi/7.webp",
			"/Residential/Vaisnavi/8.webp",
			"/Residential/Vaisnavi/9.webp",
			"/Residential/Vaisnavi/10.webp",
			"/Residential/Vaisnavi/11.webp",
			"/Residential/Vaisnavi/12.webp",
		],
	},
	Bimalji: {
		title: "Bimalji",
		src: "/Residential/Bimalji/1.webp",
		type: "Residential",
		description:
			"A classic yet contemporary residence that exudes warmth, sophistication, and timeless beauty.",
		images: [
			"/Residential/Bimalji/1.webp",
			"/Residential/Bimalji/2.webp",
			"/Residential/Bimalji/3.webp",
			"/Residential/Bimalji/4.webp",
			"/Residential/Bimalji/5.webp",
			"/Residential/Bimalji/6.webp",
			"/Residential/Bimalji/7.webp",
			"/Residential/Bimalji/8.webp",
			"/Residential/Bimalji/9.webp",
			"/Residential/Bimalji/10.webp",
			"/Residential/Bimalji/11.webp",
		],
	},
};
