export const navigationLinks = [
	{ href: "/", text: "Home" },
	{ href: "/portfolio", text: "Portfolio" },
	{ href: "/about", text: "About" },
	{ href: "/contact", text: "Contact" },
];

export const testimonials = [
	{
		quote: "Our living room is now the perfect blend of elegance and comfort. The team's expertise exceeded all our expectations!",
		name: "Ravi Patel",
		designation: "Homeowner, Bengaluru",
		src: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=3560&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
	},
	{
		quote: "Transforming our office space into a modern, productive environment was seamless with their guidance. Highly recommended!",
		name: "Ananya Sharma",
		designation: "Entrepreneur, Ahmedabad",
		src: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=3540&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
	},
	{
		quote: "The kitchen makeover was a dream come true! Every corner reflects both beauty and functionality.",
		name: "Priya Iyer",
		designation: "Chef, Chennai",
		src: "https://images.unsplash.com/photo-1623582854588-d60de57fa33f?q=80&w=3540&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
	},
	{
		quote: "Thanks to their brilliant designs, our home now feels like a luxury retreat. Exceptional work!",
		name: "Arjun Mehta",
		designation: "Architect, Mumbai",
		src: "https://images.unsplash.com/photo-1636041293178-808a6762ab39?q=80&w=3464&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
	},
	{
		quote: "The attention to detail and thoughtful layout of our new home interior has left us speechless. Absolutely delighted!",
		name: "Neha Gupta",
		designation: "IT Professional, Delhi",
		src: "https://images.unsplash.com/photo-1624561172888-ac93c696e10c?q=80&w=2592&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
	},
];

export const residentialCards = [
	{
		title: "Forest Adventure",
		src: "https://images.unsplash.com/photo-1518710843675-2540dd79065c?q=80&w=3387&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
	},
	{
		title: "Valley of life",
		src: "https://images.unsplash.com/photo-1600271772470-bd22a42787b3?q=80&w=3072&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
	},
	{
		title: "Sala behta hi jayega",
		src: "https://images.unsplash.com/photo-1505142468610-359e7d316be0?q=80&w=3070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
	},
	{
		title: "Camping is for pros",
		src: "https://images.unsplash.com/photo-1486915309851-b0cc1f8a0084?q=80&w=3387&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
	},
	{
		title: "The road not taken",
		src: "https://images.unsplash.com/photo-1507041957456-9c397ce39c97?q=80&w=3456&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
	},
	{
		title: "Forest Adventure 1",
		src: "https://images.unsplash.com/photo-1518710843675-2540dd79065c?q=80&w=3387&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
	},
	{
		title: "Valley of life 1",
		src: "https://images.unsplash.com/photo-1600271772470-bd22a42787b3?q=80&w=3072&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
	},
	{
		title: "Sala behta hi jayega 1",
		src: "https://images.unsplash.com/photo-1505142468610-359e7d316be0?q=80&w=3070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
	},
	{
		title: "Camping is for pros 1",
		src: "https://images.unsplash.com/photo-1486915309851-b0cc1f8a0084?q=80&w=3387&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
	},
	{
		title: "The road not taken 1",
		src: "https://images.unsplash.com/photo-1507041957456-9c397ce39c97?q=80&w=3456&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
	},
];

export const commercialCards = [
	{
		title: "Advantech Office",
		src: "/Commercial/Advantech Office/1.png",
	},
	{
		title: "Fizz Club House",
		src: "/Commercial/Fizz Club House/1.png",
	},
	{
		title: "Manjhu",
		src: "/Commercial/Manjhu/1.png",
	},
	{
		title: "Realstate",
		src: "/Commercial/Realstate/1.png",
	},
	{
		title: "Fire Office",
		src: "/Commercial/Fire Office/1.png",
	},
	{
		title: "Neha Vikram",
		src: "/Commercial/Neha Vikram/1.png",
	},
	{
		title: "Priynka Kolkata",
		src: "/Commercial/Priynka Kolkata/1.png",
	},
	{
		title: "Punjabi Dhaba",
		src: "/Commercial/Punjabi Dhaba/1.png",
	},
	{
		title: "Winntus",
		src: "/Commercial/Winntus/1.png",
	},
	{
		title: "Lico Industrial",
		src: "/Commercial/Lico Industrial/1.png",
	},
	{
		title: "Cafe In Delhi",
		src: "/Commercial/Cafe In Delhi/1.png",
	},

	{
		title: "Museum",
		src: "/Commercial/Museum/9.png",
	},
];

export const portfolioImages = {
	"Advantech Office": [
		"/Commercial/Advantech Office/1.png",
		"/Commercial/Advantech Office/2.png",
		"/Commercial/Advantech Office/3.png",
		"/Commercial/Advantech Office/4.png",
		"/Commercial/Advantech Office/5.png",
		"/Commercial/Advantech Office/6.png",
		"/Commercial/Advantech Office/7.png",
		"/Commercial/Advantech Office/8.png",
		"/Commercial/Advantech Office/9.png",
		"/Commercial/Advantech Office/10.png",
	],
	"Fizz Club House": [
		"/Commercial/Fizz Club House/1.png",
		"/Commercial/Fizz Club House/2.png",
		"/Commercial/Fizz Club House/3.png",
		"/Commercial/Fizz Club House/4.png",
		"/Commercial/Fizz Club House/5.png",
		"/Commercial/Fizz Club House/6.png",
		"/Commercial/Fizz Club House/7.png",
		"/Commercial/Fizz Club House/8.png",
		"/Commercial/Fizz Club House/9.png",
		"/Commercial/Fizz Club House/10.png",
		"/Commercial/Fizz Club House/11.png",
		"/Commercial/Fizz Club House/12.png",
		"/Commercial/Fizz Club House/13.png",
	],
	"Manjhu": [
		"/Commercial/Manjhu/1.png",
		"/Commercial/Manjhu/2.png",
		"/Commercial/Manjhu/3.png",
		"/Commercial/Manjhu/4.png",
		"/Commercial/Manjhu/5.png",
		"/Commercial/Manjhu/6.png",
		"/Commercial/Manjhu/7.png",
		"/Commercial/Manjhu/8.png",
	],
	"Realstate": [
		"/Commercial/Realstate/1.png",
		"/Commercial/Realstate/2.png",
		"/Commercial/Realstate/3.png",
		"/Commercial/Realstate/4.png",
		"/Commercial/Realstate/5.png",
		"/Commercial/Realstate/6.png",
		"/Commercial/Realstate/7.png",
		"/Commercial/Realstate/8.png",
		"/Commercial/Realstate/9.png",
		"/Commercial/Realstate/10.png",
		"/Commercial/Realstate/11.png",
		"/Commercial/Realstate/12.png",
	],
	"Fire Office": [
		"/Commercial/Fire Office/1.png",
		"/Commercial/Fire Office/2.png",
		"/Commercial/Fire Office/3.png",
		"/Commercial/Fire Office/4.png",
		"/Commercial/Fire Office/5.png",
		"/Commercial/Fire Office/6.png",
		"/Commercial/Fire Office/7.png",
		"/Commercial/Fire Office/8.png",
		"/Commercial/Fire Office/9.png",
		"/Commercial/Fire Office/10.png",
		"/Commercial/Fire Office/11.png",
		"/Commercial/Fire Office/12.png",
	],
	"Neha Vikram": [
		"/Commercial/Neha Vikram/1.png",
		"/Commercial/Neha Vikram/2.png",
		"/Commercial/Neha Vikram/3.png",
		"/Commercial/Neha Vikram/4.png",
		"/Commercial/Neha Vikram/5.png",
		"/Commercial/Neha Vikram/6.png",
		"/Commercial/Neha Vikram/7.png",
		"/Commercial/Neha Vikram/8.png",
	],
	"Priynka Kolkata": [
		"/Commercial/Priynka Kolkata/1.png",
		"/Commercial/Priynka Kolkata/2.png",
		"/Commercial/Priynka Kolkata/3.png",
		"/Commercial/Priynka Kolkata/4.png",
		"/Commercial/Priynka Kolkata/5.png",
		"/Commercial/Priynka Kolkata/6.png",
		"/Commercial/Priynka Kolkata/7.png",
		"/Commercial/Priynka Kolkata/8.png",
		"/Commercial/Priynka Kolkata/9.png",
	],
	"Punjabi Dhaba": [
		"/Commercial/Punjabi Dhaba/1.png",
		"/Commercial/Punjabi Dhaba/2.png",
		"/Commercial/Punjabi Dhaba/3.png",
		"/Commercial/Punjabi Dhaba/4.png",
		"/Commercial/Punjabi Dhaba/5.png",
		"/Commercial/Punjabi Dhaba/6.png",
		"/Commercial/Punjabi Dhaba/7.png",
		"/Commercial/Punjabi Dhaba/8.png",
		"/Commercial/Punjabi Dhaba/9.png",
		"/Commercial/Punjabi Dhaba/10.png",
		"/Commercial/Punjabi Dhaba/11.png",
		"/Commercial/Punjabi Dhaba/12.png",
		"/Commercial/Punjabi Dhaba/13.png",
		"/Commercial/Punjabi Dhaba/14.png",
		"/Commercial/Punjabi Dhaba/15.png",
	],
	"Winntus": [
		"/Commercial/Winntus/1.png",
		"/Commercial/Winntus/2.png",
		"/Commercial/Winntus/3.png",
		"/Commercial/Winntus/4.png",
		"/Commercial/Winntus/5.png",
		"/Commercial/Winntus/6.png",
		"/Commercial/Winntus/7.png",
		"/Commercial/Winntus/8.png",
		"/Commercial/Winntus/9.png",
		"/Commercial/Winntus/10.png",
	],
	"Lico Industrial": [
		"/Commercial/Lico Industrial/1.png",
		"/Commercial/Lico Industrial/2.png",
		"/Commercial/Lico Industrial/3.png",
		"/Commercial/Lico Industrial/4.png",
		"/Commercial/Lico Industrial/5.png",
		"/Commercial/Lico Industrial/6.png",
		"/Commercial/Lico Industrial/7.png",
		"/Commercial/Lico Industrial/8.png",
		"/Commercial/Lico Industrial/9.png",
		"/Commercial/Lico Industrial/10.png",
		"/Commercial/Lico Industrial/11.png",
		"/Commercial/Lico Industrial/12.png",
		"/Commercial/Lico Industrial/13.png",
		"/Commercial/Lico Industrial/14.png",
		"/Commercial/Lico Industrial/15.png",
	],
	"Cafe In Delhi": [
		"/Commercial/Cafe In Delhi/1.png",
		"/Commercial/Cafe In Delhi/2.png",
		"/Commercial/Cafe In Delhi/3.png",
		"/Commercial/Cafe In Delhi/4.png",
		"/Commercial/Cafe In Delhi/5.png",
		"/Commercial/Cafe In Delhi/6.png",
		"/Commercial/Cafe In Delhi/7.png",
		"/Commercial/Cafe In Delhi/8.png",
		"/Commercial/Cafe In Delhi/9.png",
	],
	"Museum": [
		"/Commercial/Museum/1.png",
		"/Commercial/Museum/2.png",
		"/Commercial/Museum/3.png",
		"/Commercial/Museum/4.png",
		"/Commercial/Museum/5.png",
		"/Commercial/Museum/6.png",
		"/Commercial/Museum/7.png",
		"/Commercial/Museum/8.png",
		"/Commercial/Museum/9.png",
		"/Commercial/Museum/10.png",
		"/Commercial/Museum/11.png",
	],
};
